### ISSUE TITLE
Try swapping Mersenne Twister for Xoshiro256++ in C++

### ISSUE THREAD

**Issue by mdmaas** [JamieMair/julia-for-research-with-hpc#3]
Hi!

This is a very interesting benchmark! 

I am not a C++ expert, but it seems that the C++ random number generator you are using in the C++ code is Mersenne Twister, which is considered obsolete (see [paper](https://arxiv.org/abs/1910.06437). 

According to the [docs](https://docs.julialang.org/en/v1/stdlib/Random/), Julia uses [Xoshiro256++](https://prng.di.unimi.it/) instead.

So yes, it seems that Julia has the best and fastest algorithms set up by default, at least in some areas.

Another way to make the benchmark would be to force Julia to use Mersenne Twister

```
rng = MersenneTwister(1234)

function simple_monte_carlo(n, T)
	x = zeros(n)	
	for i in eachindex(x)
		for t in 1:T	
			x[i] += Random.randn(rng)	
		end	
	end
	return x
end
```
In this case, I get that this Julia code is about 3x slower than your C++.

I don't know how to use Xoshiro256++ in C++, and I don't use random numbers a lot in my research area, so I leave this issue here in case somebody wants to show us how it would be done.

**Comment by mdmaas** [comment]
This was actually wrong, and the proper Julia code should have included `rng` as a function variable:

```
rng = MersenneTwister(1234)

function simple_monte_carlo(n, T, rng)
	x = zeros(n)	
	for i in eachindex(x)
		for t in 1:T	
			x[i] += Random.randn(rng)	
		end	
	end
	return x
end
```

**Comment by JamieMair** [comment]
I'll leave a link to the discourse forum where this is discussed [here](https://discourse.julialang.org/t/blog-using-julia-on-the-hpc/88039/). To summarise for anyone else seeing this link. C++ (in my implementation) using their standard library uses a Mersenne Twister algorithm and Julia uses Xoshiro256++ by default, the former is much slower than the latter. If you correct the typing (as done above), the performance of Julia still comes out ahead.

My point in the comparison is not to compare the speed of the language. If you are doing the exact same thing, the code should lower to approximately the same in both languages. The main point of this comparison is to say that Julia and C/C++ has a very similar performance ceiling, but the main difference is (specifically in this benchmark), is that the ceiling is much easier to reach in Julia (fast rng by default in standard library, and easy to manage external packages etc) for a beginner looking to learn the language. This should probably be made more clear in the article, and thanks for raising the discussion here.
